version: '3'

services:

  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    container_name: api
    stdin_open: true
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - redis


  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    container_name: client
    volumes:
       - ./client:/app
       - /app/node_modules
    stdin_open: true
    ports:
      - "5173:5173"


  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "3050:80"
    depends_on:
       - api
       - client

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
